# Generated by Django 3.2.1 on 2021-05-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название')),
                ('min_price', models.FloatField(verbose_name='Минимальная цена')),
                ('max_price', models.FloatField(verbose_name='Максимальная цена')),
                ('url', models.URLField(unique=True, verbose_name='Ссылка')),
                ('type', models.URLField(verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
